spring:
  application:
    name: cred0-core
  datasource:
    url: jdbc:h2:mem:cred0;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
